------------------------------------------------------------------------
-- DISCLAIMER:
--    This script is provided for educational purposes only. It is NOT
--	supported by Oracle World Wide Technical Support.
--    The script has been tested and appears to work as intended.
--	You should always run new scripts on a test instance initially.
--
------------------------------------------------------------------------
Insert into country (country_id,country_name,continent) values (172,'Algeria','AFRICA');
Insert into country (country_id,country_name,continent) values (173,'Egypt','AFRICA');
Insert into country (country_id,country_name,continent) values (174,'Libya','AFRICA');
Insert into country (country_id,country_name,continent) values (175,'Morocco','AFRICA');
Insert into country (country_id,country_name,continent) values (176,'Tunisia','AFRICA');
Insert into country (country_id,country_name,continent) values (179,'Republic of South Africa','AFRICA');
Insert into country (country_id,country_name,continent) values (180,'Other Sub Sahara','N/A');
Insert into country (country_id,country_name,continent) values (181,'Angola','AFRICA');
Insert into country (country_id,country_name,continent) values (182,'Benin','AFRICA');
Insert into country (country_id,country_name,continent) values (183,'Botswana','AFRICA');
Insert into country (country_id,country_name,continent) values (184,'Burkina','AFRICA');
Insert into country (country_id,country_name,continent) values (185,'Burundi','AFRICA');
Insert into country (country_id,country_name,continent) values (186,'Cameroon','AFRICA');
Insert into country (country_id,country_name,continent) values (187,'Cape Verde Islands','AFRICA');
Insert into country (country_id,country_name,continent) values (188,'Central African Republic','AFRICA');
Insert into country (country_id,country_name,continent) values (189,'Chad','AFRICA');
Insert into country (country_id,country_name,continent) values (190,'Comoros Islands','AFRICA');
Insert into country (country_id,country_name,continent) values (191,'Congo, Republic of (Brazzaville)','AFRICA');
Insert into country (country_id,country_name,continent) values (192,'Cote D''Ivoire','AFRICA');
Insert into country (country_id,country_name,continent) values (193,'Djibouti','AFRICA');
Insert into country (country_id,country_name,continent) values (194,'Equatorial Guinea','AFRICA');
Insert into country (country_id,country_name,continent) values (195,'Eritrea','AFRICA');
Insert into country (country_id,country_name,continent) values (196,'Ethiopia','AFRICA');
Insert into country (country_id,country_name,continent) values (197,'Gabon','AFRICA');
Insert into country (country_id,country_name,continent) values (198,'Gambia','AFRICA');
Insert into country (country_id,country_name,continent) values (199,'Ghana','AFRICA');
Insert into country (country_id,country_name,continent) values (200,'Guinea','AFRICA');
Insert into country (country_id,country_name,continent) values (201,'Guinea Bissau','AFRICA');
Insert into country (country_id,country_name,continent) values (202,'Kenya','AFRICA');
Insert into country (country_id,country_name,continent) values (203,'Lesotho','AFRICA');
Insert into country (country_id,country_name,continent) values (204,'Liberia','AFRICA');
Insert into country (country_id,country_name,continent) values (205,'Madagascar','AFRICA');
Insert into country (country_id,country_name,continent) values (206,'Malawi','AFRICA');
Insert into country (country_id,country_name,continent) values (207,'Mali','AFRICA');
Insert into country (country_id,country_name,continent) values (208,'Mauritania','AFRICA');
Insert into country (country_id,country_name,continent) values (209,'Mauritius','AFRICA');
Insert into country (country_id,country_name,continent) values (210,'Mozambique','AFRICA');
Insert into country (country_id,country_name,continent) values (211,'Namibia','AFRICA');
Insert into country (country_id,country_name,continent) values (212,'Niger','AFRICA');
Insert into country (country_id,country_name,continent) values (213,'Nigeria','AFRICA');
Insert into country (country_id,country_name,continent) values (214,'Rwanda','AFRICA');
Insert into country (country_id,country_name,continent) values (215,'Sao Tome and Principe','AFRICA');
Insert into country (country_id,country_name,continent) values (216,'Senegal','AFRICA');
Insert into country (country_id,country_name,continent) values (217,'Seychelles','AFRICA');
Insert into country (country_id,country_name,continent) values (218,'Sierra Leone','AFRICA');
Insert into country (country_id,country_name,continent) values (219,'Sudan','AFRICA');
Insert into country (country_id,country_name,continent) values (220,'Swaziland','AFRICA');
Insert into country (country_id,country_name,continent) values (221,'Tanzania','AFRICA');
Insert into country (country_id,country_name,continent) values (222,'Togo','AFRICA');
Insert into country (country_id,country_name,continent) values (223,'Uganda','AFRICA');
Insert into country (country_id,country_name,continent) values (224,'Zaire (Congo, Democratic Republic, Kinshasha)','AFRICA');
Insert into country (country_id,country_name,continent) values (225,'Zambia','AFRICA');
Insert into country (country_id,country_name,continent) values (226,'Zimbabwe','AFRICA');
Insert into country (country_id,country_name,continent) values (3,'North America','N/A');
Insert into country (country_id,country_name,continent) values (4,'Canada','AMERICAS');
Insert into country (country_id,country_name,continent) values (5,'United States','AMERICAS');
Insert into country (country_id,country_name,continent) values (6,'Latin America','N/A');
Insert into country (country_id,country_name,continent) values (7,'Mexico','AMERICAS');
Insert into country (country_id,country_name,continent) values (8,'Caribbean and Central America','N/A');
Insert into country (country_id,country_name,continent) values (9,'Antigua and Barbuda','AMERICAS');
Insert into country (country_id,country_name,continent) values (10,'Bahamas','AMERICAS');
Insert into country (country_id,country_name,continent) values (11,'Barbados','AMERICAS');
Insert into country (country_id,country_name,continent) values (12,'Belize','AMERICAS');
Insert into country (country_id,country_name,continent) values (13,'Bermuda','AMERICAS');
Insert into country (country_id,country_name,continent) values (14,'Costa Rica','AMERICAS');
Insert into country (country_id,country_name,continent) values (15,'Cuba','AMERICAS');
Insert into country (country_id,country_name,continent) values (16,'Dominica','AMERICAS');
Insert into country (country_id,country_name,continent) values (17,'Dominican Republic','AMERICAS');
Insert into country (country_id,country_name,continent) values (18,'El Salvador','AMERICAS');
Insert into country (country_id,country_name,continent) values (19,'Grenada','AMERICAS');
Insert into country (country_id,country_name,continent) values (20,'Guatemala','AMERICAS');
Insert into country (country_id,country_name,continent) values (21,'Haiti','AMERICAS');
Insert into country (country_id,country_name,continent) values (22,'Honduras','AMERICAS');
Insert into country (country_id,country_name,continent) values (23,'Jamaica and Dependencies','AMERICAS');
Insert into country (country_id,country_name,continent) values (24,'Nicaragua','AMERICAS');
Insert into country (country_id,country_name,continent) values (25,'Panama','AMERICAS');
Insert into country (country_id,country_name,continent) values (26,'Puerto Rico','AMERICAS');
Insert into country (country_id,country_name,continent) values (27,'St Kitts and Nevis','AMERICAS');
Insert into country (country_id,country_name,continent) values (28,'St Lucia','AMERICAS');
Insert into country (country_id,country_name,continent) values (29,'St Vincent and the Grenadines','AMERICAS');
Insert into country (country_id,country_name,continent) values (30,'Trinidad and Tobago','AMERICAS');
Insert into country (country_id,country_name,continent) values (31,'South America','AMERICAS');
Insert into country (country_id,country_name,continent) values (32,'Argentina','AMERICAS');
Insert into country (country_id,country_name,continent) values (33,'Brazil','AMERICAS');
Insert into country (country_id,country_name,continent) values (34,'Other South America','N/A');
Insert into country (country_id,country_name,continent) values (35,'Bolivia','AMERICAS');
Insert into country (country_id,country_name,continent) values (36,'Chile','AMERICAS');
Insert into country (country_id,country_name,continent) values (37,'Colombia','AMERICAS');
Insert into country (country_id,country_name,continent) values (38,'Ecuador','AMERICAS');
Insert into country (country_id,country_name,continent) values (39,'Guyana','AMERICAS');
Insert into country (country_id,country_name,continent) values (40,'Paraguay','AMERICAS');
Insert into country (country_id,country_name,continent) values (41,'Peru','AMERICAS');
Insert into country (country_id,country_name,continent) values (42,'Suriname','AMERICAS');
Insert into country (country_id,country_name,continent) values (43,'Uruguay','AMERICAS');
Insert into country (country_id,country_name,continent) values (44,'Venezuela','AMERICAS');
Insert into country (country_id,country_name,continent) values (130,'Pakistan','ASIA');
Insert into country (country_id,country_name,continent) values (131,'Other South Asia','N/A');
Insert into country (country_id,country_name,continent) values (132,'Afghanistan','ASIA');
Insert into country (country_id,country_name,continent) values (133,'Bhutan','ASIA');
Insert into country (country_id,country_name,continent) values (134,'Nepal','ASIA');
Insert into country (country_id,country_name,continent) values (135,'Sri Lanka','ASIA');
Insert into country (country_id,country_name,continent) values (155,'Iran','ASIA');
Insert into country (country_id,country_name,continent) values (156,'Iraq','ASIA');
Insert into country (country_id,country_name,continent) values (157,'Saudi Arabia','ASIA');
Insert into country (country_id,country_name,continent) values (158,'Turkey','ASIA');
Insert into country (country_id,country_name,continent) values (160,'Bahrain','ASIA');
Insert into country (country_id,country_name,continent) values (161,'Israel','ASIA');
Insert into country (country_id,country_name,continent) values (103,'Asia','ASIA');
Insert into country (country_id,country_name,continent) values (105,'East Asia','ASIA');
Insert into country (country_id,country_name,continent) values (107,'China','ASIA');
Insert into country (country_id,country_name,continent) values (108,'Hong Kong','ASIA');
Insert into country (country_id,country_name,continent) values (109,'Japan','ASIA');
Insert into country (country_id,country_name,continent) values (110,'South Korea','ASIA');
Insert into country (country_id,country_name,continent) values (111,'Taiwan','ASIA');
Insert into country (country_id,country_name,continent) values (112,'Other East Asia','ASIA');
Insert into country (country_id,country_name,continent) values (113,'Macau','ASIA');
Insert into country (country_id,country_name,continent) values (114,'Mongolia','ASIA');
Insert into country (country_id,country_name,continent) values (115,'Southeast Asia','ASIA');
Insert into country (country_id,country_name,continent) values (116,'Indonesia','ASIA');
Insert into country (country_id,country_name,continent) values (117,'Malaysia','ASIA');
Insert into country (country_id,country_name,continent) values (118,'Philippines','ASIA');
Insert into country (country_id,country_name,continent) values (119,'Thailand','ASIA');
Insert into country (country_id,country_name,continent) values (120,'Vietnam','ASIA');
Insert into country (country_id,country_name,continent) values (121,'Other Southeast Asia','N/A');
Insert into country (country_id,country_name,continent) values (122,'Brunei','ASIA');
Insert into country (country_id,country_name,continent) values (123,'Burma Myanmar','ASIA');
Insert into country (country_id,country_name,continent) values (124,'Cambodia Kampuchea Khmer','ASIA');
Insert into country (country_id,country_name,continent) values (125,'Laos','ASIA');
Insert into country (country_id,country_name,continent) values (126,'Singapore','ASIA');
Insert into country (country_id,country_name,continent) values (127,'South Asia','ASIA');
Insert into country (country_id,country_name,continent) values (128,'Bangladesh','ASIA');
Insert into country (country_id,country_name,continent) values (129,'India','ASIA');
Insert into country (country_id,country_name,continent) values (162,'Jordon','ASIA');
Insert into country (country_id,country_name,continent) values (163,'Kuwait','ASIA');
Insert into country (country_id,country_name,continent) values (164,'Lebanon','ASIA');
Insert into country (country_id,country_name,continent) values (165,'Oman','ASIA');
Insert into country (country_id,country_name,continent) values (166,'Syria','ASIA');
Insert into country (country_id,country_name,continent) values (167,'United Arab Emirates','ASIA');
Insert into country (country_id,country_name,continent) values (168,'West Bank','ASIA');
Insert into country (country_id,country_name,continent) values (169,'Yemen United','ASIA');
Insert into country (country_id,country_name,continent) values (45,'Europe','N/A');
Insert into country (country_id,country_name,continent) values (46,'European Union 27','N/A');
Insert into country (country_id,country_name,continent) values (47,'European Union 15','N/A');
Insert into country (country_id,country_name,continent) values (48,'Austria','EUROPE');
Insert into country (country_id,country_name,continent) values (49,'Belgium-Luxembourg','EUROPE');
Insert into country (country_id,country_name,continent) values (50,'Belgium','EUROPE');
Insert into country (country_id,country_name,continent) values (51,'Luxembourg','EUROPE');
Insert into country (country_id,country_name,continent) values (52,'Denmark','EUROPE');
Insert into country (country_id,country_name,continent) values (53,'Finland','EUROPE');
Insert into country (country_id,country_name,continent) values (54,'France','EUROPE');
Insert into country (country_id,country_name,continent) values (55,'Germany','EUROPE');
Insert into country (country_id,country_name,continent) values (56,'Greece','EUROPE');
Insert into country (country_id,country_name,continent) values (57,'Ireland','EUROPE');
Insert into country (country_id,country_name,continent) values (58,'Italy','EUROPE');
Insert into country (country_id,country_name,continent) values (59,'Netherlands','EUROPE');
Insert into country (country_id,country_name,continent) values (60,'Portugal','EUROPE');
Insert into country (country_id,country_name,continent) values (61,'Spain','EUROPE');
Insert into country (country_id,country_name,continent) values (62,'Sweden','EUROPE');
Insert into country (country_id,country_name,continent) values (63,'United Kingdom','EUROPE');
Insert into country (country_id,country_name,continent) values (65,'Bulgaria','EUROPE');
Insert into country (country_id,country_name,continent) values (66,'Cyprus','EUROPE');
Insert into country (country_id,country_name,continent) values (67,'Czech Republic','EUROPE');
Insert into country (country_id,country_name,continent) values (68,'Estonia','EUROPE');
Insert into country (country_id,country_name,continent) values (69,'Hungary','EUROPE');
Insert into country (country_id,country_name,continent) values (70,'Latvia','EUROPE');
Insert into country (country_id,country_name,continent) values (71,'Lithuania','EUROPE');
Insert into country (country_id,country_name,continent) values (72,'Malta and Gozo','EUROPE');
Insert into country (country_id,country_name,continent) values (73,'Poland','EUROPE');
Insert into country (country_id,country_name,continent) values (74,'Romania','EUROPE');
Insert into country (country_id,country_name,continent) values (75,'Slovakia','EUROPE');
Insert into country (country_id,country_name,continent) values (76,'Slovenia','EUROPE');
Insert into country (country_id,country_name,continent) values (77,'Other Europe','EUROPE');
Insert into country (country_id,country_name,continent) values (79,'Iceland','EUROPE');
Insert into country (country_id,country_name,continent) values (80,'Norway','EUROPE');
Insert into country (country_id,country_name,continent) values (81,'Switzerland','EUROPE');
Insert into country (country_id,country_name,continent) values (83,'Albania','EUROPE');
Insert into country (country_id,country_name,continent) values (84,'Bosnia Herzegovina','EUROPE');
Insert into country (country_id,country_name,continent) values (85,'Croatia','EUROPE');
Insert into country (country_id,country_name,continent) values (86,'Macedonia','EUROPE');
Insert into country (country_id,country_name,continent) values (87,'Serbia','EUROPE');
Insert into country (country_id,country_name,continent) values (89,'Russia','EUROPE');
Insert into country (country_id,country_name,continent) values (90,'Ukraine','EUROPE');
Insert into country (country_id,country_name,continent) values (92,'Armenia','EUROPE');
Insert into country (country_id,country_name,continent) values (93,'Azerbaijan','EUROPE');
Insert into country (country_id,country_name,continent) values (94,'Belarus','EUROPE');
Insert into country (country_id,country_name,continent) values (95,'Georgia','EUROPE');
Insert into country (country_id,country_name,continent) values (96,'Kazakhstan','EUROPE');
Insert into country (country_id,country_name,continent) values (97,'Kyrgyzstan','EUROPE');
Insert into country (country_id,country_name,continent) values (98,'Moldova','EUROPE');
Insert into country (country_id,country_name,continent) values (99,'Tajikistan','EUROPE');
Insert into country (country_id,country_name,continent) values (100,'Turkmenistan','EUROPE');
Insert into country (country_id,country_name,continent) values (101,'Uzbekistan','EUROPE');
Insert into country (country_id,country_name,continent) values (153,'Other Asia/Oceania','N/A');
Insert into country (country_id,country_name,continent) values (154,'Middle East','N/A');
Insert into country (country_id,country_name,continent) values (159,'Other Middle East','N/A');
Insert into country (country_id,country_name,continent) values (1,'World','N/A');
Insert into country (country_id,country_name,continent) values (2,'World Less US','N/A');
Insert into country (country_id,country_name,continent) values (64,'A12','N/A');
Insert into country (country_id,country_name,continent) values (78,'Other Western Europe','N/A');
Insert into country (country_id,country_name,continent) values (82,'Other Central Europe','N/A');
Insert into country (country_id,country_name,continent) values (88,'Former Soviet Union','N/A');
Insert into country (country_id,country_name,continent) values (91,'Other Former Soviet ','N/A');
Insert into country (country_id,country_name,continent) values (102,'Asia and Oceania','N/A');
Insert into country (country_id,country_name,continent) values (104,'Asia less Japan','N/A');
Insert into country (country_id,country_name,continent) values (106,'East Asia less Japan','N/A');
Insert into country (country_id,country_name,continent) values (170,'Africa','N/A');
Insert into country (country_id,country_name,continent) values (171,'North Africa','N/A');
Insert into country (country_id,country_name,continent) values (177,'Other North Africa/Middle East','N/A');
Insert into country (country_id,country_name,continent) values (178,'Sub-Saharan Africa','N/A');
Insert into country (country_id,country_name,continent) values (229,'Developed','N/A');
Insert into country (country_id,country_name,continent) values (230,'Developed less US','N/A');
Insert into country (country_id,country_name,continent) values (231,'Developing','N/A');
Insert into country (country_id,country_name,continent) values (232,'Graduated Developed','N/A');
Insert into country (country_id,country_name,continent) values (233,'High Income Oil Exporters','N/A');
Insert into country (country_id,country_name,continent) values (234,'Developing less Graduated and Oil Exporters','N/A');
Insert into country (country_id,country_name,continent) values (235,'Former Centrally Planned','N/A');
Insert into country (country_id,country_name,continent) values (236,'Emerging Markets','N/A');
Insert into country (country_id,country_name,continent) values (237,'Developing and Formerly Centrally Planned','N/A');
Insert into country (country_id,country_name,continent) values (136,'Oceania','OCEANIA');
Insert into country (country_id,country_name,continent) values (137,'Australia','OCEANIA');
Insert into country (country_id,country_name,continent) values (138,'New Zealand','OCEANIA');
Insert into country (country_id,country_name,continent) values (139,'Other Oceania','OCEANIA');
Insert into country (country_id,country_name,continent) values (140,'Fiji','OCEANIA');
Insert into country (country_id,country_name,continent) values (141,'French Polynesia','OCEANIA');
Insert into country (country_id,country_name,continent) values (142,'Kiribati and Tuvalu Gilbert Islands','OCEANIA');
Insert into country (country_id,country_name,continent) values (143,'Maldives Islands','OCEANIA');
Insert into country (country_id,country_name,continent) values (144,'Marshall Islands','OCEANIA');
Insert into country (country_id,country_name,continent) values (145,'Micronesia, Federated States of','OCEANIA');
Insert into country (country_id,country_name,continent) values (146,'New Caledonia','OCEANIA');
Insert into country (country_id,country_name,continent) values (147,'Palau','OCEANIA');
Insert into country (country_id,country_name,continent) values (148,'Papua New Guinea','OCEANIA');
Insert into country (country_id,country_name,continent) values (149,'Samoa','OCEANIA');
Insert into country (country_id,country_name,continent) values (150,'Solomon Islands','OCEANIA');
Insert into country (country_id,country_name,continent) values (151,'Tonga','OCEANIA');
Insert into country (country_id,country_name,continent) values (152,'Vanuatu New Hebrides','OCEANIA');
commit;
